name: seustudyassist
description: Collect virtual Demo question papers per subject. Easily see what subjects you need to take in any semester from our application and give suggestions. CGP calculator. Social Connection & Universities that have clubs can join all clubs from our application.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  bloc:
  flutter_bloc: ^8.1.4
  


  
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.0
  velocity_x: ^4.1.2
  sliding_clipped_nav_bar: ^3.1.0+4
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.5
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^4.2.1
  lottie: ^3.1.0
  webview_flutter: ^2.0.13
  dio: ^5.4.1
  dash_chat_2: ^0.0.20
  http: 1.2.0
  ionicons: ^0.2.2
  table_calendar: ^3.0.9
  connectivity_plus: ^3.0.2
  open_file: ^3.3.2
  pdf: ^3.10.8
  get: ^4.6.6
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  circular_menu: ^3.0.0
  flutter_pdfview: ^1.3.2
  loading_animation_widget: ^1.2.1
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  fluttertoast: ^8.2.5
  printing: ^5.12.0
  dropdown_button2: ^2.3.9
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true


  assets:
    - assets/
    - assets/images/university_logo/
    - assets/logos/
    - assets/fonts/
    - assets/animations/
  


  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf

